name: Docker Image CI

on:
  push:
    branches: [ groovy ]
  pull_request:
    branches: [ groovy ]
  schedule:
    - cron: '0 0 * * *' # Auto build Docker every midnight

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag latest:$(date +%s)
    
    - name: send telegram message
      run: |
          function sendTG() {
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown"
          }
          sendTG "\`I have pushed new images to docker\` %0A ${{ secrets.LINK2 }}" &> /dev/null
